package com.basics.threads;

public class ResultTask extends Thread{
    @Override
    public void run(){
        System.out.println("result generated by:"+Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t1=new ResultTask();
        t1.run();//no new thread created
        t1.start();// new thread -thread 0 is created

    }
}
/*
Points to remember:
start() multithreading -multitasking-concurrency
run()- normal Execution
start()-internally calls run()
Thread cannot be started twice
Thread
 */
